### ISSUE TITLE
make a way to run both backend and frontend in dev

### ISSUE THREAD

**Issue by lorypelli** [vclemenzi/vite-plugin-multip#11]
I'd like to use the backend without build the frontend before, maybe try to make some "fake dist" folder that will be replaced when building with the real one...

**Comment by clemenzi** [comment]
You can utilize `vite build -w` to rebuild every time a file changes. I'm not keen on the idea of having a `dist` directory for development mode.

**Comment by lorypelli** [comment]
> You can utilize `vite build -w` to rebuild every time a file changes. I'm not keen on the idea of having a `dist` directory for development mode.

The problem is that the page doesn't auto-reload when I make a change like it do is dev, and when I reload, I loose the content that was added by clicking buttons with javascript in frontend
