### ISSUE TITLE
allow filename to be either `index`, `main` or `page`

### ISSUE THREAD

**Issue by lorypelli** [vclemenzi/vite-plugin-multip#18]
Option in the config, what should be default one?

**Comment by clemenzi** [comment]
That's a good idea, I'd probably leave `index` as the default name, but I'll think about it

**Comment by lorypelli** [comment]
> That's a good idea, I'd probably leave `index` as the default name, but I'll think about it

I think it's the best idea to work correctly if users are already using it or you can just make no config option and allow both, I also like this idea

**Comment by lorypelli** [comment]
Added `main` because it's commonly used on react

**Comment by clemenzi** [comment]
I've thought about it a bit, and I don't see the direct need for this feature, it requires some big changes from a code standpoint (and will probably even create bugs), considering `index` is the standard in the web, we'll use that. This feature might be reconsidered in the future, but currently not. Thanks anyway for the idea.
