### ISSUE TITLE
Tailwind support 

### ISSUE THREAD

**Issue by abhijitgujar86** [vclemenzi/vite-plugin-multip#26]
While the import runds good how can we configure Tailwind in project ?

**Comment by clemenzi** [comment]
You can set up Tailwind CSS with Vite by following the [official guide](https://tailwindcss.com/docs/guides/vite). Once the setup is complete, create a `layout.css` file in the pages directory and include the Tailwind CSS directives. If you encounter any issues during the setup, please let me know.
