### ISSUE TITLE
React with windows issue

### ISSUE THREAD

**Issue by lorypelli** [vclemenzi/vite-plugin-multip#27]
![image](https://github.com/user-attachments/assets/9f7dfbcf-764a-49a2-9c9d-2c5b92b769b8)
The plugin doesn't work with React on Windows

**Comment by clemenzi** [comment]
This should be fixed with version `1.1.7`

**Comment by lorypelli** [comment]
> This should be fixed with version `1.1.7`

Ok, thanks, are you able to update github release?
